// Generated by CoffeeScript 1.9.2
var gulp;

gulp = require('gulp');

gulp.task('default', ['copy'], function() {});


/* copy bower_compenets */

gulp.task('copy', ['copy-jquery', 'copy-require', 'copy-bootstrap'], function() {
  var copy;
  copy = require('gulp-copy');
  return gulp.src('./bower_components/requirejs/require.js').pipe(copy('./build/js/', {
    prefix: 2
  }));
});


/* copy requirejs */

gulp.task('copy-jquery', function() {
  var copy;
  copy = require('gulp-copy');
  return gulp.src('./bower_components/jquery/dist/jquery.js').pipe(copy('./build/js/', {
    prefix: 3
  }));
});


/* copy requirejs */

gulp.task('copy-require', function() {
  var copy;
  copy = require('gulp-copy');
  return gulp.src('./bower_components/requirejs/require.js').pipe(copy('./build/js/', {
    prefix: 2
  }));
});


/* copy requirejs */

gulp.task('copy-bootstrap', function() {
  var copy;
  copy = require('gulp-copy');
  return gulp.src('./bower_components/bootstrap/dist/**/*').pipe(copy('./build/bootstrap/', {
    prefix: 3
  }));
});
